### PR TITLE
[FIX] history diff compare in reversed order

### LINKED ISSUE #104: Version comparison from 'History' is in reversed order
The comparison feature, which is utilized by opening the history bar, compares the history version in the reveresed order. As the following shows, the left, which highlighted in red as a deletion, is actually the latest updating.

image
 

The green part should be the latest updating, thus the comparison result might be more naturally. 

1. Create a template project.
2. Do some modification
3. Open the History bar in bottom left

### Environment
 - **Overleaf Workshop Extension version**: 0.9.1
 - **VS Code version**: 1.86.2
 - **Overleaf Edition**:  Community

<details>
  ...
</details>

### PR DESCRIPTION
**Pull request by iamhyc**
> resolves #104

### CODE REVIEW

**Comment by iamhyc** [comment]
@QianrenLi Hi, please help check if all the three diff situation are fixed with correct order. Thank you!

The three situations are:
1. compare (selected one) with previous version
2. compare (selected one) with current version
3. compare (selected one) with another selected version

**Comment by QianrenLi** [comment]
1. Compare with previous version / Automatical Comparison by clicking version: **Comparison is correct. The order shows above seems to be different from the bottom**
image
2. Comapare with current version: **The listed order is correct, the comparison is not**
image
3. Compare with selected version: **Same result to 'Comapare with current version'**

**Comment by iamhyc** [comment]
@QianrenLi I am confused. Do you mean in all the three situation, the diff order is correct, but the order in title is still wrong?

**Comment by QianrenLi** [comment]
Sorry for the confusion, in conclusion, only the **compare (selected one) with previous version** is wrong in the archived version (0.9.1), and the modification also needs contain the title order. 
As for situation 2 and 3, the modification done in the PR seems to hurt the original correct comparison order.

**Comment by iamhyc** [comment]
If I got you correctly, only "compare with previous version" needs to be fixed. Please check the latest commit.

**Review by QianrenLi — APPROVED** [review]

**Pull request merged**
